baseURL = "https://juliafmorgado.com"
title = "Julia Furst Morgado"


# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatol"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[social]
  twitter = "juliafmorgado"

[params]
profilePicture = "https://blog-imgs-23.s3.amazonaws.com/julia.jpg"
description = """
JULIA FURST MORGADO
"""
favicon = "favicons/"
copyright = "Julia F Morgado {{ YEAR }}"
customCss = ["css/custom.css"]
readMore = false
relatedPosts = true
numberOfRelatedPosts = 3
gtagId = "G-H2FSKPLDX2"
hidesidebar = true

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/juliafmorgado"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/juliafmorgado"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/juliafmorgado"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/c/JuliaFMorgado"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/juliafmorgado/"

[[params.socialIcons]]
icon = "fab fa-tiktok"
title = "Tik Tok"
url = "https://www.tiktok.com/@juliafmorgado"


[menu]
  # English Menu
  [[languages.en.menu.main]]
  name = "Blog"
  identifier = "home"
  weight = 100
  url = "/"

  [[languages.en.menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[languages.en.menu.main]]
  name = "Talks"
  weight = 300
  identifier = "talks"
  url = "https://github.com/juliafmorgado/talks"

  [[languages.en.menu.main]]
  name = "Collab"
  weight = 400
  identifier = "collab"
  url = "/collab/"

 # French Menu
  [[languages.fr.menu.main]]
  name = "Blog"
  identifier = "home"
  weight = 100
  url = "/fr/"

  [[languages.fr.menu.main]]
  name = "À propos de moi"
  weight = 200
  identifier = "about"
  url = "/fr/about/"

  [[languages.fr.menu.main]]
  name = "Conférences"
  weight = 300
  identifier = "talks"
  url = "https://github.com/juliafmorgado/talks"
  
  [[languages.fr.menu.main]]
  name = "Collab"
  weight = 400
  identifier = "collab"
  url = "/fr/collab/"

  # Portuguese Menu
  [[languages.pt.menu.main]]
  name = "Blog"
  identifier = "home"
  weight = 100
  url = "/pt/"

  [[languages.pt.menu.main]]
  name = "Sobre mim"
  weight = 200
  identifier = "about"
  url = "/pt/about/"

  [[languages.pt.menu.main]]
  name = "Palestras"
  weight = 300
  identifier = "talks"
  url = "https://github.com/juliafmorgado/talks"

  [[languages.pt.menu.main]]
  name = "Collab"
  weight = 400
  identifier = "collab"
  url = "/pt/collab/"

# Spanish Menu
  [[languages.es.menu.main]]
  name = "Blog"
  identifier = "home"
  weight = 100
  url = "/es/"

  [[languages.es.menu.main]]
  name = "Acerca de mí"
  weight = 200
  identifier = "about"
  url = "/es/about/"

  [[languages.es.menu.main]]
  name = "Charlas"
  weight = 300
  identifier = "talks"
  url = "https://github.com/juliafmorgado/talks"

  [[languages.es.menu.main]]
  name = "Collab"
  weight = 400
  identifier = "collab"
  url = "/es/collab/"

[mermaid]
enable = true

[languages]
  [languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/english" 

  [languages.fr]
  languageName = "Français"
  weight = 2
  contentDir = "content/french" 

  [languages.pt]
  languageName = "Português"
  weight = 3
  contentDir = "content/portuguese" 

  [languages.es]
  languageName = "Español"
  weight = 4
  contentDir = "content/spanish" 
